version: '2.3'
services:
  mongodb:
    image: mongo:4.0.5
    restart: unless-stopped
    container_name: gsmongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./database/data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --noauth --bind_ip_all --oplogSize 128
    networks:
      - geeksessions-network
  gsfrontend:
    image: gsfrontend_develop
    container_name: gsfrontend_develop
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - mongodb
      - gsbackend
    networks:
      - geeksessions-network
  gsbackend:
    image: gsbackend_develop
    container_name: gsbackend_develop
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    restart: always
    depends_on:
      - mongodb
    command: sh -c '/wait-for mongodb:27017 -- npm run start:dev'
    networks:
      - geeksessions-network
networks:
  geeksessions-network:
    driver: bridge